server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_SERVICE_URL}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customerService
          uri: lb://customerService
          predicates:
            - Path=/api/v1/customers/**
        - id: creditsService
          uri: lb://creditsService
          predicates:
            - Path=/api/v1/credits/**
        - id: accountBanksService
          uri: lb://accountBanksService
          predicates:
            - Path=/api/v1/accountBanks/**